image: lorisleiva/laravel-docker:8.2

# Variables
variables:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: laravel
  DB_HOST: mysql
  DB_USERNAME: root
  GIT_STRATEGY: clone

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.init_ssh_dev: &init_ssh_dev |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
      - git config --global --add safe.directory $CI_PROJECT_DIR
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env

npm:
  stage: build
  image: node:18-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
    policy: pull-push
  script:
      - npm install
      - npm run build
  artifacts:
    expire_in: 1 month
    paths:
      - node_modules/
      - public/css/
      - public/js/

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app
  only:
    - testing # or the name of your main branch

phpunit:
  stage: test
  services:
    - name: mysql:5.7
  image: chilio/laravel-dusk-ci:php-8.2
  dependencies:
    - composer
  script:
    - cp .env.example .env
    - composer install
    - npm install
    - npm run build
    - configure-laravel
    - start-nginx-ci-project
    - sleep 3
    - php ./vendor/bin/phpunit --testsuite=Feature
  only:
    - testing # or the name of your main branch

staging:
  stage: deploy
  script:
    - *init_ssh_dev
    - *change_file_permissions
    - vendor/bin/dep deploy
  environment:
    name: staging
    url: http://lms.n2rdev.in/
  only:
    - main
  
production:
  stage: deploy
  script:
    - *init_ssh
    - *change_file_permissions
    - vendor/bin/dep deploy production
  environment:
    name: production
    url: https://kaolin.n2rdev.in/
  only:
   - live